- name: gnome | packages | install gnome packages
  tags: gnome,gnome-packages
  package:
    name:
      # - eog
      # - file-roller
      # - "{{ gdm_package }}"
      # - gedit
      - gnome-backgrounds
      # - gnome-books
      # - gnome-boxes
      - gnome-control-center
      - gnome-disk-utility
#      - gnome-documents
      - gnome-icon-theme
#      - gnome-music
#      - gnome-photos
      # - gnome-power-manager
      # - gnome-remote-desktop
      # - gnome-shell
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-terminal
      # - gnome-todo
      - gnome-tweaks
      - nautilus