# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yaml"
  tags: always

- block:
  # Desktop Configuration
  - import_tasks: desktop/gnome/appearance.yaml
    when:
      - desktop is defined
      - desktop == "gnome"

  # Shell Configuration
  - import_tasks: users/sudoers.yaml
  - import_tasks: software/zsh.yaml
    when:
      - zsh is defined
      - zsh == true

  # Developer Software
  - import_tasks: software/gitkraken.yaml
    when:
      - gitkraken is defined
      - gitkraken == true
  - import_tasks: software/vscode.yaml
    when:
      - vscode is defined
      - vscode == true

  # General Software
  - import_tasks: software/solaar.yaml
    when:
      - solaar is defined
      - solaar == true
  # Install gnome tweaks

  # Internet Browser Software
  - import_tasks: software/chromium.yaml
    when:
      - chromium is defined
      - chromium == true
  - import_tasks: software/firefox.yaml
    when:
      - firefox is defined
      - firefox == true
  - import_tasks: software/google_chrome.yaml
    when:
      - google_chrome is defined
      - google_chrome == true

  # HashiCorp Software
  - import_tasks: software/packer.yaml
    when:
      - packer is defined
      - packer == true
  - import_tasks: software/terraform.yaml
    when:
      - terraform is defined
      - terraform == true
  - import_tasks: software/vagrant.yaml
    when:
      - vagrant is defined
      - vagrant == true
  - import_tasks: software/vault.yaml
    when:
      - vault is defined
      - vault == true
