- name: software | firefox | install package
  tags: packages,firefox,flatpak,workstation-packages
  become_user: "{{ install_user }}"
  flatpak:
    name: org.mozilla.firefox
    method: user
    state: present
