- name: software | python | apt dependancies
  apt:
    state: present
    pkg:
      - python3
      - python3-venv
      - python3-pip

- name: software | python | install pip packages
  pip:
    name: "{{ item }}"
  loop:
    - psutil