- name: software | visual-studio-code | add repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  when: 
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: software | visual-studio-code | add repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/ stable main"
    filename: vscode
  register: vscode_repo
  when: 
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: software | visual-studio-code | update sources (repo added or changed)
  apt:
    update_cache: yes
  changed_when: False
  when: 
    - vscode_repo.changed

- name: software | visual-studio-code | install package
  apt:
    name: code
  when: 
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]